server.port= 8092
spring.application.name= ConfigServer_NewsNest

#spring.cloud.config.server.git.uri= https://gitlab-cts.stackroute.in/Manoj.BT/news-nest
#spring.cloud.config.server.git.username= Manoj.BT
#spring.cloud.config.server.git.password= *****
#spring.cloud.config.server.git.default-label= config_file_for_UserProfile
#spring.cloud.config.server.git.clone-on-start= true

spring.cloud.config.server.git.uri= https://gitlab-cts.stackroute.in/Manoj.BT/news-nest
spring.cloud.config.server.git.username= Manoj.BT
spring.cloud.config.server.git.password= *****
spring.cloud.config.server.git.default-label= config_file_for_UserProfile
spring.cloud.config.server.git.clone-on-start= true

management.security.enable= false
management.endpoints.web.exposure.include= *


eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true
