
server.port = 8999
spring.application.name = AuthService_NewsNest

#MySQL Configurations
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/AuthService_NewsNest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

jwt.secret = secret

app.jwttoken.message =  Login Successful
app.controller.exception.message1= Id and Password Empty
app.controller.exception.message2= Id and Password not found
app.controller.exception.message3= Id and Password invalid
app.service.message1= User Already Exists
app.service.message2= Invalid Id and Password


eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true

#Kafka Configurations
spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=authgroup
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer


logging.file.name= authservice/logs/AuthService