server.port= 8082
spring.application.name= NewsService_NewsNest

jwt.secret = secret

eureka.client.register-with-eureka = true
eureka.client.fetch-registry = true


logging.file.name= newsservice/logs/NewsService