package com.cts.newsnest.authservice.controller;

import com.cts.newsnest.authservice.domain.CompleteUser;
import com.cts.newsnest.authservice.exception.UserAlreadyExistException;
import com.cts.newsnest.authservice.exception.UserNotFoundException;
import com.cts.newsnest.authservice.domain.User;
import com.cts.newsnest.authservice.service.UserService;
import com.cts.newsnest.authservice.config.JWTTokenGenerator;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.Map;

@CrossOrigin("*")
@RestController
@RequestMapping("/api/v1/")
public class UserController {

    private UserService userService;
    private JWTTokenGenerator jwtTokenGenerator;
    ResponseEntity<?> responseEntity;

    @Value("${app.controller.exception.message1}")
    private String message1;

    @Value("${app.controller.exception.message2}")
    private String message2;

    @Value("${app.controller.exception.message3}")
    private String message3;


    @Autowired
    public UserController(UserService userService, JWTTokenGenerator jwtTokenGenerator) {
        this.userService = userService;
        this.jwtTokenGenerator = jwtTokenGenerator;
    }

    @ExceptionHandler(UserAlreadyExistException.class)
    public ResponseEntity<?> handleUserAlreadyExistException(UserAlreadyExistException ex){
        return new ResponseEntity<>(ex.getMessage(), HttpStatus.CONFLICT);
    }

    @ExceptionHandler(UserNotFoundException.class)
    public ResponseEntity<?> handleUserNotFoundException(UserNotFoundException ex){
        return new ResponseEntity<>(ex.getMessage(), HttpStatus.UNAUTHORIZED);
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<?> handleException(Exception ex){
        return new ResponseEntity<>("An Error occurred: " +ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
    }

    @ResponseStatus(HttpStatus.BAD_REQUEST)
    @ExceptionHandler(MethodArgumentNotValidException.class)
    public Map<String, String> handleValidationException(MethodArgumentNotValidException exception){
        Map <String, String> errors = new HashMap<>();
        exception.getBindingResult().getAllErrors().forEach((error) ->{
            String fieldName = ((FieldError) error).getField();
            String errorMessage = error.getDefaultMessage();
            errors.put(fieldName, errorMessage);
        });
        return  errors;
    }

    @PostMapping("/register")
    public ResponseEntity<?> RegisterUser(@Valid @RequestBody CompleteUser completeUser) throws Exception{
        User savedUser;
        try{
            return new ResponseEntity<>(userService.registerUser(completeUser), HttpStatus.CREATED);
        }
        catch (UserAlreadyExistException ex){
            throw ex;
        }
        catch (Exception ex){
            throw new RuntimeException(ex);
        }

    }


//    @PostMapping("login/user")
//    public ResponseEntity<?> loginUser(@Valid @RequestBody User user) {
//        try {
//
//            User userDetails = userService.findByIdAndPassword(user.getEmail(), user.getPassword());
//            if (userDetails == null) {
//                throw new UserNotFoundException(message2);
//            }
//            if (!(user.getPassword().equals(userDetails.getPassword()))) {
//                throw new UserNotFoundException(message3);
//            }
//            /*
//             * Create ResponseEntity with token generated by calling generateToken method of JwtTokenGenerator
//             */
////            Map<?,?> responseEntity = jwtTokenGenerator.generateToken(user);
//            return new ResponseEntity<>(jwtTokenGenerator.generateToken(user),HttpStatus.OK);
//        } catch (UserNotFoundException e) {
//            responseEntity = new ResponseEntity<>(e.getMessage(), HttpStatus.CONFLICT);
//        }
//        return responseEntity;
//    }

    @PostMapping("/login/user")
    public ResponseEntity<?> loginUser(@Valid @RequestBody User user) throws Exception{
        try{
            return new ResponseEntity<>(userService.loginUser(user), HttpStatus.OK);
        }
        catch (UserNotFoundException ex){
            throw ex;
        }
        catch (Exception ex){
            throw new RuntimeException(ex);
        }
    }
}
