server.port = 8085
spring.application.name = UserProfile_NewsNest

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/UserProfile_NewsNest?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Root@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

eureka.client.register-with-eureka= true
eureka.client.fetch-registry= true

spring.cloud.config.enabled= false

#spring.cloud.compatibility-verifier.enabled=false

#spring.config.import=optional:configserver:http://localhost:8092

#management.endpoints.web.exposure.include= *

#spring.cloud.config.uri=http://localhost:8091


spring.kafka.producer.bootstrap-servers= localhost:9092
spring.kafka.consumer.group-id=GroupOfUserProfile
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer= org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer= org.apache.kafka.common.serialization.StringSerializer


logging.file.name= user/logs/User